name = input("Insert your Full Name: ")
age = input("Age: ")
city = input("city: ")
university = input("university: ")
department=input("Department: ")
language = input("Favorite programming language: ")
goal = input("What is your One programming goal: ")

print ("="*35)
print("    STUDENT INTRODUCTION")
print ("="*35)

print(f"My name is {name}.\n I am {age} years old. \nI live in {city}. ")
print(f"I study {department} at {university}.")
print(f"My favorite programming language is {language}.")
print("\nMy programming goal:")
print(goal)
print ("="*35)