full_name=input("Full Name: ")
age=int(input("Age: "))
student_id = input("Enter your ID: ")
city = input("city: ")
university = input("University: ")
department=input("Department: ")
email = input("Email: ")
phone = input("Phone Number: ")
language = input("Favorite programming language: ")
goal = input("What is your programming goal: ")

print ("="*55)
print(f"{'AKIBA STUDENT PROFILE':^55}")
print ("="*55)
print (""*55)

print(f"Name: {full_name}")
print(f"Student ID: {student_id}")
print(f"Age: {age}")
print(f"City: {city}")
print(f"University: {university}")
print(f"Departement: {department}")
print(f"Email: {email}")
print(f"Phone: {phone}")
print(f"Favorite Language: {language}")

print("\nProgramming Goal: ")
print(goal)

print (""*55)
print ("="*55)